### ISSUE TITLE
No Module Named “MySQLdb”

### ISSUE THREAD

**Issue by formero009** [fsistemas/sql2json#1]
Hi there, I got a problem by using your sql2json tool, I need your help.
When I was trying to run the command to test install, I got this error
![image](https://user-images.githubusercontent.com/25760739/83711562-223c5900-a656-11ea-8b09-05e99e8f4561.png)

The command is:
python -m sql2json --name mysql --query xdr_http

config file:
{
    "conections": {
        "mysql": "mysql+pymysql://root:root@localhost/test"
    },
    "queries": {
        "xdr_http": "SELECT * FROM xdr_http"
    }
}
I had searched that error tried to fixed it, and tried to install that module but only work on python2,
my python version is 3.7.6.
So is there anyone got the same problem? pls help me

**Comment by fsistemas** [comment]
Hi @formero009,

1. The error No module named 'MySQLdb' only happen when in config file i have:
"mysql": "mysql://root:root@localhost/test"

2. When i have:
"mysql": "mysql+pymysql://root:root@localhost/test"

The error is: No module named 'pymysql'

To solve the second issue you need to install 'pymysql' module using: pip install PyMySQL

Test again and let me know if that works.

**NOTE**
If your issue continue, please run this command **echo %HOME%** and send me the full path where you have the sql2json config file.

**Comment by formero009** [comment]
Hi Mate @fsistemas:
       Thanks for your response. sorry for replay late. Got sth else to do.
       That error happened because I installed PyMySQL not correctly. now I have fixed that problem, your tools is very convenient btw love it  already star it thanks again. have a nice one

**Comment by fsistemas** [comment]
Hi @formero009, 

I'm happy sql2json is useful for you.

Fell free to open a new issue if you have any question or you want to give me some feedback.

Regards
