### ISSUE TITLE
what sql dialect you do support 

### ISSUE THREAD

**Issue by Sandy4321** [fsistemas/sql2json#2]
what sql dialect you do support 
MS server 
or
oracle
or
mysql

**Comment by fsistemas** [comment]
@Sandy4321  sql2json uses sqlalchemy, so you can any sql dialect supported by sqlalchemy. 

If you need to use mysql then you install mysql driver, if you need oracle you install oracle driver, etc.

sqlalchemy dialects: https://docs.sqlalchemy.org/en/13/dialects/

**Comment by fsistemas** [comment]
Closing this issue.

If you have any other question feel free to open a new issue.

Regards
